# nginx proxy address - http://172.17.0.1:25600

name: komga
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  komga:
    image: gotson/komga:latest
    pull_policy: always
    container_name: komga-app
    restart: always
    user: "${SERVICE_USER:-1000}:${SERVICE_GROUP:-1000}"
    logging: *default-logging
    networks:
      - komga
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:25600:25600"
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: komga-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    volumes:
      - ./volumes/config/komga:/config
      - ./volumes/data/komga:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:25600"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://komga-app:25600'
      - 'cloudflare.hostname=komga.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.komga-app.entrypoints=http'
      - 'traefik.http.routers.komga-app-secure.tls=true'
      - 'traefik.http.routers.komga-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.komga-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.komga-app.middlewares=komga-app-https-redirect'
      - 'traefik.http.routers.komga-app-secure.entrypoints=https'
      - 'traefik.http.routers.komga-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.komga-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.komga-app-secure.service=komga-app'
      - 'traefik.http.services.komga-app.loadbalancer.server.port=25600'

networks:
  komga:
    name: komga
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
